# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=modulith;Username=postgres;Password=postgres;
    depends_on:
      - postgres
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: modulith
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
